const MSG = {
  DB_CONNECTED: 'Database connected successfully',

  AUTH: {
    SELF: 'SELF',
    USER_REGISTERED: 'USER_REGISTERED',
    USER_VERIFIED: 'USER_VERIFIED',
    USER_LOGGED_IN: 'USER_LOGGED_IN',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    RESET_PASSWORD: 'RESET_PASSWORD',
    USER_UPDATED_FULL_NAME: 'USER_UPDATED_FULL_NAME',
    USER_UPDATED_AVATAR: 'USER_UPDATED_AVATAR',
  },

  PROJECT: {
    GET_PROJECT: 'GET_PROJECT',
    UPDATE_PROJECT: 'UPDATE_PROJECT',
    CREATE_PROJECT: 'CREATE_PROJECT',
    DELETE_PROJECT: 'DELETE_PROJECT',
    GET_PROJECTS: 'GET_PROJECTS',
  },

  MEMBER: {
    GET_MEMBERS: 'GET_MEMBERS',
    GET_MEMBER: 'GET_MEMBER',
    CREATE_MEMBER: 'CREATE_MEMBER',
    UPDATE_MEMBER: 'UPDATE_MEMBER',
    DELETE_MEMBER: 'DELETE_MEMBER',
  },
}

export default MSG
