const MSG = {
  DB_CONNECTED: 'Database connected successfully',

  AUTH: {
    SELF: 'SELF',
    USER_REGISTERED: 'USER_REGISTERED',
    USER_VERIFIED: 'USER_VERIFIED',
    USER_LOGGED_IN: 'USER_LOGGED_IN',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    RESET_PASSWORD: 'RESET_PASSWORD',
    USER_UPDATED_FULL_NAME: 'USER_UPDATED_FULL_NAME',
    USER_UPDATED_AVATAR: 'USER_UPDATED_AVATAR',
  },

  PROJECT: {
    GET_PROJECT: 'GET_PROJECT',
    UPDATE_PROJECT: 'UPDATE_PROJECT',
    CREATE_PROJECT: 'CREATE_PROJECT',
    DELETE_PROJECT: 'DELETE_PROJECT',
    GET_PROJECTS: 'GET_PROJECTS',
  },

  MEMBER: {
    GET_MEMBERS: 'GET_MEMBERS',
    GET_MEMBER: 'GET_MEMBER',
    CREATE_MEMBER: 'CREATE_MEMBER',
    UPDATE_MEMBER: 'UPDATE_MEMBER',
    REMOVE_MEMBER: 'REMOVE_MEMBER',
  },

  TASK: {
    GET_TASKS: 'GET_TASKS',
    GET_TASK: 'GET_TASK',
    CREATE_TASK: 'CREATE_TASK',
    UPDATE_TASK: 'UPDATE_TASK',
    DELETE_TASK: 'DELETE_TASK',
    ASSIGN_MEMBER: 'ASSIGN_MEMBER',
    REMOVE_ASSINGED_MEMBER: 'REMOVE_ASSINGED_MEMBER',
    CREATE_COMMENT: 'CREATE_COMMENT',
  },
}

export default MSG
